### INFO: https://www.meilisearch.com/docs/reference/api/indexes


### Creates an index

POST http://localhost:7700/indexes HTTP/1.1
Content-Type: application/json

{
  "primaryKey": "id",
  "uid": "movies"
}


### Gets all indexes

GET http://localhost:7700/indexes HTTP/1.1
Content-Type: application/json


### Gets an index settings

GET http://localhost:7700/indexes/movies/settings HTTP/1.1
Content-Type: application/json
